# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-auth0-connection
  description: Auth 0 Connection component
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








